ARG COREOS_VERSION="${COREOS_VERSION:-stable}"

FROM quay.io/fedora/fedora-coreos:${COREOS_VERSION}

ARG COREOS_VERSION="${COREOS_VERSION:-stable}"

RUN echo "Installing dependencies" && \
    rpm-ostree install \
        binutils \
        cmake \
        python3-pip \
        gcc-c++ \
        gettext \
        diffstat \
        doxygen \
        git \
        patch \
        patchutils \
        subversion \
        systemtap \
        buildbot \
        colordiff \
        cvs \
        cvs2cl \
        cvsps \
        darcs \
        dejagnu \
        expect \
        gambas3-ide \
        git-annex \
        git-cola \
        git2cl \
        gitg \
        gtranslator \
        highlight \
        lcov \
        manedit \
        meld \
        monotone \
        myrepos \
        nemiver \
        qgit \
        quilt \
        rapidsvn \
        rcs \
        robodoc \
        scanmem \
        subunit \
        svn2cl \
        tig \
        tortoisehg \
        translate-toolkit \
        utrac \
        gcc \
        openssl-devel \
        bzip2-devel \
        elfutils-devel \
        libselinux-devel \
        elfutils-libelf-devel \
        rpm-devel \
        perl-devel \
        python3-devel \
        python3-setuptools \
        chrpath \
        mariadb-connector-c-devel \
        glib2-devel \
        gpgme-devel \
        gnutls-devel \
        libgcrypt-devel \
        libuuid-devel \
        libssh-devel \
        hiredis-devel \
        libxml2-devel \
        libpcap-devel \
        libnet-devel \
        paho-c-devel \
        openldap-devel \
        radcli-devel \
        postgresql-server \
        postgresql-server-devel \
        postgresql-contrib \
        wget \
        sshpass \
        samba-client \
        python3-lxml \
        gnutls-utils \
        perl \
        perl-XML-Twig \
        libmicrohttpd-devel \
        popt-devel \
        libunistring-devel \
        ncurses-devel \
        heimdal-devel \
        bison \
        libksba-devel \
        nmap \
        json-glib-devel \
        python3-impacket \
        python3 \
        python3-setuptools \
        python3-packaging \
        python3-wrapt \
        python3-cffi \
        python3-psutil \
        python3-defusedxml \
        python3-paramiko \
        python3-redis \
        python3-gnupg \
        python3-paho-mqtt \
        redis \
        policycoreutils-python-utils \
        mosquitto \
        cronie \
        texlive-fontsize \
        texlive-fonttable \
        fontawesome-fonts \
        gnupg2-smime \
        xmlstarlet \
        zip \
        fakeroot \
        dpkg \
        mingw64-nsis \
        mingw64-gcc \
        wget \
        sshpass \
        samba-client \
        python3-lxml \
        gnutls-utils \
        perl \
        perl-XML-Twig \
        libmicrohttpd-devel \
        popt-devel \
        libunistring-devel \
        ncurses-devel \
        heimdal-devel \
        bison \
        libksba-devel \
        nmap \
        json-glib-devel \
        python3-impacket \
        python3 \
        python3-setuptools \
        python3-packaging \
        python3-wrapt \
        python3-cffi \
        python3-psutil \
        python3-defusedxml \
        python3-paramiko \
        python3-redis \
        python3-gnupg \
        python3-paho-mqtt \
        redis \
        policycoreutils-python-utils

COPY *.sh /tmp/

# RUN echo "Installing dependencies" && \
#     chmod +x /tmp/install-deps.sh &&  \
#     /tmp/install-deps.sh

RUN ln -sf /usr/bin/ld.bfd /etc/alternatives/ld && ln -sf /etc/alternatives/ld /usr/bin/ld && ld --version

RUN mkdir -p /var/lib/alternatives \
    && chmod +x /tmp/install-greenbone-ce-fedora-coreos.sh \
    && /tmp/install-greenbone-ce-fedora-coreos.sh \
    && mv /var/lib/alternatives /staged-alternatives \
    && rm -fr /tmp/* \
    && ostree container commit \
    && mkdir -p /var/lib && mv /staged-alternatives /var/lib/alternatives \
    && mkdir -p /tmp /var/tmp \
    && chmod -R 1777 /tmp /var/tmp