services:
  vulnerability-tests:
    image: greenbone/vulnerability-tests
    environment:
      STORAGE_PATH: /var/lib/openvas/22.04/vt-data/nasl
    volumes:
      - /greenbone/vt_data_vol:/mnt

  notus-data:
    image: greenbone/notus-data
    volumes:
      - /greenbone/notus_data_vol:/mnt

  scap-data:
    image: greenbone/scap-data
    volumes:
      - /greenbone/scap_data_vol:/mnt

  cert-bund-data:
    image: greenbone/cert-bund-data
    volumes:
      - /greenbone/cert_data_vol:/mnt

  dfn-cert-data:
    image: greenbone/dfn-cert-data
    volumes:
      - /greenbone/cert_data_vol:/mnt
    depends_on:
      - cert-bund-data

  data-objects:
    image: greenbone/data-objects
    volumes:
      - /greenbone/data_objects_vol:/mnt

  report-formats:
    image: greenbone/report-formats
    volumes:
      - /greenbone/data_objects_vol:/mnt
    depends_on:
      - data-objects

  gpg-data:
    image: greenbone/gpg-data
    volumes:
      - /greenbone/gpg_data_vol:/mnt

  redis-server:
    image: greenbone/redis-server
    restart: on-failure
    volumes:
      - /greenbone/redis_socket_vol:/run/redis/

  pg-gvm:
    image: greenbone/pg-gvm:stable
    restart: on-failure
    volumes:
      - /greenbone/psql_data_vol:/var/lib/postgresql
      - /greenbone/psql_socket_vol:/var/run/postgresql

  gvmd:
    image: greenbone/gvmd:stable
    restart: on-failure
    volumes:
      - /greenbone/gvmd_data_vol:/var/lib/gvm
      - /greenbone/scap_data_vol:/var/lib/gvm/scap-data/
      - /greenbone/cert_data_vol:/var/lib/gvm/cert-data
      - /greenbone/data_objects_vol:/var/lib/gvm/data-objects/gvmd
      - /greenbone/vt_data_vol:/var/lib/openvas/plugins
      - /greenbone/psql_data_vol:/var/lib/postgresql
      - /greenbone/gvmd_socket_vol:/run/gvmd
      - /greenbone/ospd_openvas_socket_vol:/run/ospd
      - /greenbone/psql_socket_vol:/var/run/postgresql
    depends_on:
      pg-gvm:
        condition: service_started
      scap-data:
        condition: service_completed_successfully
      cert-bund-data:
        condition: service_completed_successfully
      dfn-cert-data:
        condition: service_completed_successfully
      data-objects:
        condition: service_completed_successfully
      report-formats:
        condition: service_completed_successfully

  gsa:
    image: greenbone/gsa:stable
    restart: on-failure
    ports:
      - localhost:9392:80
    volumes:
      - /greenbone/gvmd_socket_vol:/run/gvmd
    depends_on:
      - gvmd

  ospd-openvas:
    image: greenbone/ospd-openvas:stable
    restart: on-failure
    hostname: ospd-openvas.local
    cap_add:
      - NET_ADMIN # for capturing packages in promiscuous mode
      - NET_RAW # for raw sockets e.g. used for the boreas alive detection
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    command:
      [
        "ospd-openvas",
        "-f",
        "--config",
        "/etc/gvm/ospd-openvas.conf",
        "--mqtt-broker-address",
        "mqtt-broker",
        "--notus-feed-dir",
        "/var/lib/notus/advisories",
        "-m",
        "666"
      ]
    volumes:
      - /greenbone/gpg_data_vol:/etc/openvas/gnupg
      - /greenbone/vt_data_vol:/var/lib/openvas/plugins
      - /greenbone/notus_data_vol:/var/lib/notus
      - /greenbone/ospd_openvas_socket_vol:/run/ospd
      - /greenbone/redis_socket_vol:/run/redis/
    depends_on:
      redis-server:
        condition: service_started
      gpg-data:
        condition: service_completed_successfully
      vulnerability-tests:
        condition: service_completed_successfully

  mqtt-broker:
    restart: on-failure
    image: greenbone/mqtt-broker
    networks:
      default:
        aliases:
          - mqtt-broker
          - broker

  notus-scanner:
    restart: on-failure
    image: greenbone/notus-scanner:stable
    volumes:
      - /greenbone/notus_data_vol:/var/lib/notus
      - /greenbone/gpg_data_vol:/etc/openvas/gnupg
    environment:
      NOTUS_SCANNER_MQTT_BROKER_ADDRESS: mqtt-broker
      NOTUS_SCANNER_PRODUCTS_DIRECTORY: /var/lib/notus/products
    depends_on:
      - mqtt-broker
      - gpg-data
      - vulnerability-tests

  gvm-tools:
    image: greenbone/gvm-tools
    volumes:
      - /greenbone/gvmd_socket_vol:/run/gvmd
      - /greenbone/ospd_openvas_socket_vol:/run/ospd
    depends_on:
      - gvmd
      - ospd-openvas

volumes:
  gpg_data_vol:
  scap_data_vol:
  cert_data_vol:
  data_objects_vol:
  gvmd_data_vol:
  psql_data_vol:
  vt_data_vol:
  notus_data_vol:
  psql_socket_vol:
  gvmd_socket_vol:
  ospd_openvas_socket_vol:
  redis_socket_vol: